# Generated by Django 5.2.7 on 2025-10-30 16:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (1-100) o Monto Fijo en COP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor de Descuento')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Compra mínima requerida en COP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Mínimo de Compra')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento máximo aplicable (solo para porcentajes)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Descuento Máximo')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que se puede usar este cupón', null=True, verbose_name='Límite de Usos Total')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Número máximo de veces que cada usuario puede usar este cupón', verbose_name='Límite por Usuario')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Cupón',
                'verbose_name_plural': 'Usos de Cupones',
                'ordering': ['-used_at'],
            },
        ),
    ]
