# Generated by Django 5.1.2 on 2025-10-30 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la tienda')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la tienda')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/logos/')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vendedor verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Ventas totales')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
