# Generated by Django 5.2.7 on 2025-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones de pedidos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotional_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones promocionales'),
        ),
    ]
