# Generated by Django 5.2.7 on 2025-10-30 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('other', 'Otra')], default='visa', max_length=20)),
                ('card_holder', models.CharField(max_length=200, verbose_name='Titular de la tarjeta')),
                ('card_number', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=2)),
                ('is_default', models.BooleanField(default=False, verbose_name='Tarjeta predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
