# Generated by Django 5.2.7 on 2025-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo alternativo'),
        ),
    ]
